#### NumPy di Python adalah library (pustaka) yang digunakan untuk mengolah data numerik dengan cepat dan efisien, terutama untuk operasi matriks, vektor, dan array.

In [4]:
# bisa instal numpy 
# !pip install numpy

In [5]:
import numpy as np #np itu alias agar cukup memanggil np untuk numpy

## Create array using numpy
## Create 1Dimension Array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)   # Karena single dimension jadi hanya keluar satu angka yaitu 5, blank


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
## 2D Array
arr2=np.array([1,2,3,4,5])  # ini masih 1D array
arr2.reshape(1,5)           # ini di reshape menjadi 2D Array, 2D array punya [[]]. 1,5 artinya 1 row dan 5 column sesuai element awal

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])    # lst inside a lst
print(arr2)
print(arr2.shape)                           # Output (2,5) artinya 2 rows, 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
# buat element 0-10 dengan kondisi skip setiap 1 element
# Element diubah menggunakan reshape menjadi 2D dengan kondisi 5 rows, 1 column

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))  # Membuat 2D array (()) dengan kondisi 3 rows, 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## Identity matrix on array

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Atributes dari numpy

arr = np.array([[1, 2, 3],[4, 5, 6]])

print("array:\n", arr)
print("Shape:", arr.shape)                      # Output (2,3)
print("Number of dimension", arr.ndim)          # Output 2
print("Size (number of element):", arr.size)    # Output 6
print("Data type:", arr.dtype)                  # Output: int64
print("item size (in bytes):", arr.itemsize)    # Output 8

array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension 2
Size (number of element): 6
Data type: int64
item size (in bytes): 8


In [12]:
### Numpy Vectorized Operation

arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([10, 20, 30, 40, 50])

## Element Addition

print("Addition:", arr1 + arr2)

## ELement substarction

print("Substraction:", arr1 - arr2)

## Element Multiplication

print("Multiplication:", arr1 * arr2)

## Element Division

print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
## Artinya sebuah function yang di aplikasikan ke semua array yang ada

arr=np.array([1,2,3,4,5])

# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [14]:
## array slicing dan indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# Cara ambil element 1
# Harus tau lokasi rows dan column secara spesifik

arr[0]  # Artinya rows dari index 0

array([1, 2, 3, 4])

In [16]:
# Cara ambil element 1
print(arr[0][0])

1


In [17]:
# Cara ambil element 7, 8, 11, 12
arr[1:,2:]         # ":" artinya sampai dengan tak terhingga atau dispesifikkan

array([[ 7,  8],
       [11, 12]])

In [23]:
# Cara ambil element 3,4,7,8
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [41]:
# Cara ambil element 6,7,10,11
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [42]:
## Modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
arr[1:]=100

In [44]:
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
## Statistical Concept -- Normalization
## Change data a mean of 0 standart deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

# Normalized the data

normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [59]:
## Logical Operation
## Biasanya dipakai saat mengunakan Panda

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data>=8)]

array([ 8,  9, 10])